// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    // Invoke the tsx binary directly rather than through `pnpm tsx` - the
    // production runtime image doesn't have pnpm installed (only the
    // packages themselves), so a pnpm-wrapped command fails there even
    // though it works fine in local dev where pnpm is on PATH.
    seed: 'node_modules/.bin/tsx ./prisma/seed.ts',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
